Movielens:
  MatrixFactorization:
    BestParameters:
      batch_size: 64
      embedding_dim: 20
      epochs: 100
      learning_rate: 0.002
      weight_decay: 0.0
    BestRMSE: 0.9303441013021461
