Movielens:
  MatrixFactorization:
    BestParameters:
      batch_size: 512
      embedding_dim: 60
      epochs: 200
      learning_rate: 0.0001
      weight_decay: 0.0
    BestRMSE: 0.9334702030936937
