Movielens:
  MatrixFactorization:
    BestParameters:
      batch_size: 512
      embedding_dim: 50
      epochs: 200
      learning_rate: 0.001
      weight_decay: 0.0001
    BestRMSE: 1.0145528562904411
