Movielens:
  AutoEncoder:
    BestParameters:
      batch_size: 1024
      embedding_dim: 250
      epochs: 500
      hidden_dim: 256
      learning_rate: 0.01
      weight_decay: 0.001
    BestRMSE: 0.9363961715066758
  MLP:
    BestParameters:
      batch_size: 1024
      embedding_dim: 30
      epochs: 20
      hidden_dims:
      - 62
      - 32
      learning_rate: 0.01
      weight_decay: 0.001
    BestRMSE: 0.9330343062624212
  MatrixFactorization:
    BestParameters:
      batch_size: 1024
      embedding_dim: 40
      epochs: 100
      learning_rate: 0.001
      weight_decay: 0.001
    BestRMSE: 1.276511571608323
  NMF:
    BestParameters:
      batch_size: 1024
      epochs: 800
      latent_factors: 50
      learning_rate: 0.001
      weight_decay: 0.001
    BestRMSE: 1.1951579573712974
  RNN:
    BestParameters:
      batch_size: 512
      embedding_dim: 30
      epochs: 80
      hidden_dim: 100
      learning_rate: 0.001
      num_layers: 1
      weight_decay: 0.0001
    BestRMSE: 0.9383374288671722
  SVD:
    BestParameters:
      batch_size: 1024
      embedding_dim: 80
      epochs: 800
      learning_rate: 0.001
      weight_decay: 0.001
    BestRMSE: 0.940300414646994
MusicalInstruments:
  MatrixFactorization:
    BestParameters:
      batch_size: 1024
      embedding_dim: 40
      epochs: 100
      learning_rate: 0.001
      weight_decay: 0.001
    BestRMSE: 3.727030918583667
  NMF:
    BestParameters:
      batch_size: 1024
      epochs: 500
      latent_factors: 50
      learning_rate: 0.001
      weight_decay: 0.001
    BestRMSE: 4.412683430173939
