Movielens:
  AutoEncoder:
    BestParameters:
      batch_size: 1024
      embedding_dim: 250
      epochs: 500
      hidden_dim: 256
      learning_rate: 0.01
      weight_decay: 0.001
    BestRMSE: 0.9363961715066758
  MLP:
    BestParameters:
      batch_size: 1024
      embedding_dim: 10
      epochs: 50
      hidden_dim: 32
      learning_rate: 0.01
      weight_decay: 0.001
    BestRMSE: 0.9343398875397783
  MatrixFactorization:
    BestParameters:
      batch_size: 1024
      embedding_dim: 40
      epochs: 100
      learning_rate: 0.001
      weight_decay: 0.001
    BestRMSE: 1.276511571608323
  NMF:
    BestParameters:
      batch_size: 1024
      epochs: 800
      latent_factors: 50
      learning_rate: 0.001
      weight_decay: 0.001
    BestRMSE: 1.1951579573712974
  SVD:
    BestParameters:
      batch_size: 1024
      embedding_dim: 80
      epochs: 800
      learning_rate: 0.001
      weight_decay: 0.001
    BestRMSE: 0.940300414646994
MusicalInstruments:
  MatrixFactorization:
    BestParameters:
      batch_size: 1024
      embedding_dim: 40
      epochs: 100
      learning_rate: 0.001
      weight_decay: 0.001
    BestRMSE: 3.727030918583667
  NMF:
    BestParameters:
      batch_size: 1024
      epochs: 500
      latent_factors: 50
      learning_rate: 0.001
      weight_decay: 0.001
    BestRMSE: 4.412683430173939
