GridSearch:
  MatrixFactorization:
    embedding_dim: [40, 80]
    learning_rate: [0.001]
    weight_decay: [0.001]
    epochs: [100]
    batch_size: [1024]

  NMF:
    latent_factors: [15, 50]
    learning_rate: [0.01, 0.001]
    epochs: [50, 100, 500, 800]
    batch_size: [1024]
    weight_decay: [0.001, 0.01]

  SVD:
    embedding_dim: [40, 80, 160]
    learning_rate: [0.001, 0.01] 
    weight_decay: [0.001, 0.0001] 
    epochs: [100, 500, 800]  
    batch_size: [1024]