GridSearch:
  MatrixFactorization:
    embedding_dim: [40, 100]
    learning_rate: [0.001, 0.001]
    weight_decay: [0.0, 0.0001]
    epochs: [10]
    batch_size: [1024]

  NMF:
    latent_factors: [15, 50]
    learning_rate: [0.01, 0.001]
    epochs: [10]
    batch_size: [512]
    weight_decay: [0.001, 0.01]