GridSearch:
  MatrixFactorization:
    embedding_dim: [40, 80, 160, 250]
    learning_rate: [0.001, 0.01] 
    weight_decay: [0.001, 0.0001] 
    epochs: [100, 500, 800]  
    batch_size: [1024]

  NMF:
    latent_factors: [50, 100, 180, 250]
    learning_rate: [0.1, 0.01, 0.001]
    epochs: [100, 500, 800]
    batch_size: [1024]
    weight_decay: [0.0001, 0.001, 0.01]

  SVD:
    embedding_dim: [40, 80, 160, 250]
    learning_rate: [0.001, 0.01] 
    weight_decay: [0.001, 0.0001] 
    epochs: [100, 500, 800]  
    batch_size: [1024]

  AutoEncoder:
    embedding_dim: [40, 80, 160, 250]
    hidden_dim: [256, 512, 1024]
    learning_rate: [0.001, 0.01] 
    weight_decay: [0.001, 0.0001] 
    epochs: [200, 500, 800]  
    batch_size: [1024]
  
  MLP:
    embedding_dim: [10, 20, 30]
    hidden_dims: 
    - [62, 32]
    - [128, 64, 32]
    learning_rate: [0.001, 0.01, 0.1]
    epochs: [20, 50, 100]
    weight_decay: [0.001, 0.0001]
    batch_size: [1024]

  RNN:
    embedding_dim: [30, 50,60]
    hidden_dim: [50, 100]
    num_layers: [1, 2]
    learning_rate: [0.001, 0.01]
    batch_size: [512]
    epochs: [40, 80, 160]
    weight_decay: [0.0001, 0.0]